
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.lb||(g.lb=0);g.lb++;
(function(a){function b(n,u,v){var t=new XMLHttpRequest;t.open("GET",n,!0);t.responseType="arraybuffer";t.onprogress=function(p){var w=u;p.total&&(w=p.total);if(p.loaded){t.$a?g.Wa[n].loaded=p.loaded:(t.$a=!0,g.Wa||(g.Wa={}),g.Wa[n]={loaded:p.loaded,total:w});var D=w=p=0,M;for(M in g.Wa){var E=g.Wa[M];p+=E.total;w+=E.loaded;D++}p=Math.ceil(p*g.lb/D);g.setStatus&&g.setStatus("Downloading data... ("+w+"/"+p+")")}else!g.Wa&&g.setStatus&&g.setStatus("Downloading data...")};t.onerror=function(){throw Error("NetworkError for: "+
n);};t.onload=function(){if(200==t.status||304==t.status||206==t.status||0==t.status&&t.response)v(t.response);else throw Error(t.statusText+" : "+t.responseURL);};t.send(null)}function c(n){console.error("package error:",n)}function d(){function n(p,w,D){this.start=p;this.Kb=w;this.audio=D}function u(p){if(!p)throw"Loading data file failed."+Error().stack;if(!(p instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;p=new Uint8Array(p);n.prototype.Mb=p;p=a.files;for(var w=0;w<
p.length;++w)n.prototype.$a[p[w].filename].onload();g.removeRunDependency("datafile_kiss.data")}g.FS_createPath("/","html5",!0,!0);g.FS_createPath("/html5","assets",!0,!0);n.prototype={$a:{},open:function(p,w){this.name=w;this.$a[w]=this;g.addRunDependency("fp "+this.name)},onload:function(){this.Lb(this.Mb.subarray(this.start,this.Kb))},Lb:function(p){g.FS_createDataFile(this.name,null,p,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.$a[this.name]=null}};for(var v=a.files,t=0;t<v.length;++t)(new n(v[t].start,
v[t].end,v[t].audio)).open("GET",v[t].filename);g.addRunDependency("datafile_kiss.data");g.Eb||(g.Eb={});g.Eb["kiss.data"]={mc:!1};k?(u(k),k=null):h=u}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,l("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("kiss.data",""):"kiss.data",f=a.remote_package_size,h=null,k=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;k||b(e,f,function(n){h?(h(n),h=null):k=n},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/html5/baseSprite-webgl2.frag",
start:0,end:276,audio:0},{filename:"/html5/baseSprite-webgl2.vert",start:276,end:496,audio:0},{filename:"/html5/baseSprite.frag",start:496,end:760,audio:0},{filename:"/html5/baseSprite.vert",start:760,end:1006,audio:0},{filename:"/html5/assets/asd.wav",start:1006,end:12135,audio:1},{filename:"/html5/assets/Gui.atlas",start:12135,end:15251,audio:0},{filename:"/html5/assets/Gui.png",start:15251,end:19960,audio:0}],remote_package_size:19960,package_uuid:"e9716723-a8c1-45ea-9ddb-f90fa794cd94"});
const m=document.querySelector("#canvas");var q=0,r=0,x=1,y=1,aa=[];
function ba(a,b){m.width=a;m.height=b;a=window.addEventListener;a("resize",ca,!1);ca(null);a("keydown",e=>{e.repeat||da(0,e.keyCode);8!==e.keyCode&&9!==e.keyCode||e.preventDefault()});a("keyup",e=>{da(1,e.keyCode)});a("keypress",e=>{da(2,e.keyCode)});a("mousedown",e=>{ea(0,e.button,(e.clientX-q)*x,(e.clientY-r)*y)});a("mouseup",e=>{ea(1,e.button,(e.clientX-q)*x,(e.clientY-r)*y)});a("mousemove",e=>{ea(2,0,(e.clientX-q)*x,(e.clientY-r)*y)});a("wheel",e=>{fa(Math.sign(e.deltaY))});const c="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";").includes(navigator.platform)||
navigator.userAgent.includes("Mac")&&"ontouchend"in document;var d=[];a("touchstart",e=>{e.stopPropagation();e.preventDefault();let f;if(c)for(let k=0;k<e.changedTouches.length;k++){f=e.changedTouches[k];var h=d.indexOf(-1);-1==h&&(h=d.length);d[h]=f.identifier;z(0,h,(f.clientX-q)*x,(f.clientY-r)*y)}else for(h=0;h<e.changedTouches.length;h++)f=e.changedTouches[h],z(0,f.identifier,(f.clientX-q)*x,(f.clientY-r)*y)});a("touchend",e=>{e.preventDefault();let f;if(c)for(let k=0;k<e.changedTouches.length;k++){f=
e.changedTouches[k];var h=d.indexOf(f.identifier);d[h]=-1;z(1,h,(f.clientX-q)*x,(f.clientY-r)*y)}else for(h=0;h<e.changedTouches.length;h++)f=e.changedTouches[h],z(1,f.identifier,(f.clientX-q)*x,(f.clientY-r)*y)});a("touchmove",e=>{e.preventDefault();let f;if(c)for(let k=0;k<e.changedTouches.length;k++){f=e.changedTouches[k];var h=d.indexOf(h);z(2,h,(f.clientX-q)*x,(f.clientY-r)*y)}else for(h=0;h<e.changedTouches.length;h++)f=e.changedTouches[h],z(2,f.identifier,(f.clientX-q)*x,(f.clientY-r)*y)});
a("gamepadconnected",function(e){let f=(navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[])[e.wb.index];aa[e.wb.index]=new Float32Array(f.axes.length+f.buttons.length)});a("gamepaddisconnected",function(e){aa[e.wb.index]=void 0})}
function ha(){{let e=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:[],f;let h;for(let k=0;k<aa.length;++k)if(f=aa[k],void 0!==f){var a=e[k];var b=a.axes;h=b.length;for(var c=0;c<h;++c){var d=.05<Math.abs(b[c])?b[c]:0;.02<Math.abs(f[c]-d)&&(ia(k,c,d),f[c]=d)}a=a.buttons;for(c=0;c<a.length;++c)d=f[h],b=a[c].pressed*a[c].value,d!=b&&(ja(k,c,b),f[h]=b),h++}}ka();window.requestAnimationFrame(ha)}
function ca(){la(0,0);ma(window.innerWidth,window.innerHeight);const a=m.getBoundingClientRect();q=a.left;r=a.top;x=m.width/a.width;y=m.height/a.height}var na={},A;for(A in g)g.hasOwnProperty(A)&&(na[A]=g[A]);var oa=[],pa="./this.program";function qa(a,b){throw b;}var B="",ra;document.currentScript&&(B=document.currentScript.src);B=0!==B.indexOf("blob:")?B.substr(0,B.lastIndexOf("/")+1):"";ra=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
var sa=g.print||console.log.bind(console),l=g.printErr||console.warn.bind(console);for(A in na)na.hasOwnProperty(A)&&(g[A]=na[A]);na=null;g.arguments&&(oa=g.arguments);g.thisProgram&&(pa=g.thisProgram);g.quit&&(qa=g.quit);var ta;g.wasmBinary&&(ta=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&C("no native wasm support detected");var F,ua,va=!1,wa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function xa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&wa)return wa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function ya(a,b){return a?xa(G,a,b):""}
function H(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var k=a.charCodeAt(++f);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Aa(a){var b=za(a)+1,c=Ba(b);H(a,I,c,b);return c}var Ca,I,G,Da,Ea,J,Fa,K,Ga;
function Ha(a){Ca=a;g.HEAP8=I=new Int8Array(a);g.HEAP16=Da=new Int16Array(a);g.HEAP32=J=new Int32Array(a);g.HEAPU8=G=new Uint8Array(a);g.HEAPU16=Ea=new Uint16Array(a);g.HEAPU32=Fa=new Uint32Array(a);g.HEAPF32=K=new Float32Array(a);g.HEAPF64=Ga=new Float64Array(a)}var Ia=g.INITIAL_MEMORY||134217728;g.wasmMemory?F=g.wasmMemory:F=new WebAssembly.Memory({initial:Ia/65536,maximum:32768});F&&(Ca=F.buffer);Ia=Ca.byteLength;Ha(Ca);var Ja=[],Ka=[],La=[],Ma=[];
function Na(){var a=g.preRun.shift();Ja.unshift(a)}var Oa=Math.abs,Pa=Math.ceil,Qa=Math.floor,Ra=Math.min,L=0,Sa=null,Ta=null;function Ua(){L++;g.monitorRunDependencies&&g.monitorRunDependencies(L)}function Va(){L--;g.monitorRunDependencies&&g.monitorRunDependencies(L);if(0==L&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}g.preloadedImages={};g.preloadedAudios={};
function C(a){if(g.onAbort)g.onAbort(a);l(a);va=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Wa(){var a=Xa;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Xa="kiss.wasm";if(!Wa()){var Ya=Xa;Xa=g.locateFile?g.locateFile(Ya,B):B+Ya}
function Za(){try{if(ta)return new Uint8Array(ta);throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}function $a(){return ta||"function"!==typeof fetch?Promise.resolve().then(Za):fetch(Xa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Xa+"'";return a.arrayBuffer()}).catch(function(){return Za()})}
var ab,bb,gb={58807:function(){var a={Tb:1},b=m.getContext("webgl",a);if(b){var c=cb(db),d={qc:c,attributes:a,version:a.Tb,rb:b};b.canvas&&(b.canvas.cc=d);db[c]=d;("undefined"===typeof a.Ob||a.Ob)&&eb(d);a=c}else a=0;fb=db[a];g.jc=N=fb&&fb.rb},58827:function(){ha()}};function hb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Pb;"number"===typeof c?void 0===b.kb?ua.get(c)():ua.get(c)(b.kb):c(void 0===b.kb?null:b.kb)}}}
function ib(a){this.Za=a-16;this.ac=function(b){J[this.Za+8>>2]=b};this.Yb=function(b){J[this.Za+0>>2]=b};this.Zb=function(){J[this.Za+4>>2]=0};this.Xb=function(){I[this.Za+12>>0]=0};this.$b=function(){I[this.Za+13>>0]=0};this.yb=function(b,c){this.ac(b);this.Yb(c);this.Zb();this.Xb();this.$b()}}function jb(){return 0<jb.Ib}
function kb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function O(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function lb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function mb(a){if("/"===a)return"/";a=O(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function nb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){C("randomDevice")}}
function ob(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var pb=[];function qb(a,b){pb[a]={input:[],Oa:[],Ya:b};rb(a,sb)}
var sb={open:function(a){var b=pb[a.node.hb];if(!b)throw new P(43);a.Na=b;a.seekable=!1},close:function(a){a.Na.Ya.flush(a.Na)},flush:function(a){a.Na.Ya.flush(a.Na)},read:function(a,b,c,d){if(!a.Na||!a.Na.Ya.xb)throw new P(60);for(var e=0,f=0;f<d;f++){try{var h=a.Na.Ya.xb(a.Na)}catch(k){throw new P(29);}if(void 0===h&&0===e)throw new P(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Na||!a.Na.Ya.pb)throw new P(60);try{for(var e=
0;e<d;e++)a.Na.Ya.pb(a.Na,b[c+e])}catch(f){throw new P(29);}d&&(a.node.timestamp=Date.now());return e}},ub={xb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=tb(b)}return a.input.shift()},pb:function(a,b){null===b||10===b?(sa(xa(a.Oa,0)),a.Oa=[]):0!=b&&a.Oa.push(b)},flush:function(a){a.Oa&&0<a.Oa.length&&
(sa(xa(a.Oa,0)),a.Oa=[])}},vb={pb:function(a,b){null===b||10===b?(l(xa(a.Oa,0)),a.Oa=[]):0!=b&&a.Oa.push(b)},flush:function(a){a.Oa&&0<a.Oa.length&&(l(xa(a.Oa,0)),a.Oa=[])}},Q={Qa:null,Ra:function(){return Q.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new P(63);Q.Qa||(Q.Qa={dir:{node:{Ua:Q.Ka.Ua,Pa:Q.Ka.Pa,ab:Q.Ka.ab,gb:Q.Ka.gb,Gb:Q.Ka.Gb,jb:Q.Ka.jb,Hb:Q.Ka.Hb,Fb:Q.Ka.Fb,ib:Q.Ka.ib},stream:{Va:Q.La.Va}},file:{node:{Ua:Q.Ka.Ua,Pa:Q.Ka.Pa},
stream:{Va:Q.La.Va,read:Q.La.read,write:Q.La.write,sb:Q.La.sb,Bb:Q.La.Bb,Db:Q.La.Db}},link:{node:{Ua:Q.Ka.Ua,Pa:Q.Ka.Pa,fb:Q.Ka.fb},stream:{}},tb:{node:{Ua:Q.Ka.Ua,Pa:Q.Ka.Pa},stream:wb}});c=xb(a,b,c,d);16384===(c.mode&61440)?(c.Ka=Q.Qa.dir.node,c.La=Q.Qa.dir.stream,c.Ja={}):32768===(c.mode&61440)?(c.Ka=Q.Qa.file.node,c.La=Q.Qa.file.stream,c.Ma=0,c.Ja=null):40960===(c.mode&61440)?(c.Ka=Q.Qa.link.node,c.La=Q.Qa.link.stream):8192===(c.mode&61440)&&(c.Ka=Q.Qa.tb.node,c.La=Q.Qa.tb.stream);c.timestamp=
Date.now();a&&(a.Ja[b]=c);return c},nc:function(a){if(a.Ja&&a.Ja.subarray){for(var b=[],c=0;c<a.Ma;++c)b.push(a.Ja[c]);return b}return a.Ja},oc:function(a){return a.Ja?a.Ja.subarray?a.Ja.subarray(0,a.Ma):new Uint8Array(a.Ja):new Uint8Array(0)},ub:function(a,b){var c=a.Ja?a.Ja.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ja,a.Ja=new Uint8Array(b),0<a.Ma&&a.Ja.set(c.subarray(0,a.Ma),0))},Vb:function(a,b){if(a.Ma!=b)if(0==b)a.Ja=null,a.Ma=0;else{if(!a.Ja||a.Ja.subarray){var c=
a.Ja;a.Ja=new Uint8Array(b);c&&a.Ja.set(c.subarray(0,Math.min(b,a.Ma)))}else if(a.Ja||(a.Ja=[]),a.Ja.length>b)a.Ja.length=b;else for(;a.Ja.length<b;)a.Ja.push(0);a.Ma=b}},Ka:{Ua:function(a){var b={};b.kc=8192===(a.mode&61440)?a.id:1;b.rc=a.id;b.mode=a.mode;b.uc=1;b.uid=0;b.pc=0;b.hb=a.hb;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ma:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.fc=new Date(a.timestamp);b.sc=new Date(a.timestamp);b.ic=new Date(a.timestamp);b.Nb=4096;
b.hc=Math.ceil(b.size/b.Nb);return b},Pa:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Q.Vb(a,b.size)},ab:function(){throw yb[44];},gb:function(a,b,c,d){return Q.createNode(a,b,c,d)},Gb:function(a,b,c){if(16384===(a.mode&61440)){try{var d=zb(b,c)}catch(f){}if(d)for(var e in d.Ja)throw new P(55);}delete a.parent.Ja[a.name];a.name=c;b.Ja[c]=a;a.parent=b},jb:function(a,b){delete a.Ja[b]},Hb:function(a,b){var c=zb(a,b),d;for(d in c.Ja)throw new P(55);
delete a.Ja[b]},Fb:function(a){var b=[".",".."],c;for(c in a.Ja)a.Ja.hasOwnProperty(c)&&b.push(c);return b},ib:function(a,b,c){a=Q.createNode(a,b,41471,0);a.link=c;return a},fb:function(a){if(40960!==(a.mode&61440))throw new P(28);return a.link}},La:{read:function(a,b,c,d,e){var f=a.node.Ja;if(e>=a.node.Ma)return 0;a=Math.min(a.node.Ma-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===I.buffer&&(f=!1);if(!d)return 0;
a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ja||a.Ja.subarray)){if(f)return a.Ja=b.subarray(c,c+d),a.Ma=d;if(0===a.Ma&&0===e)return a.Ja=b.slice(c,c+d),a.Ma=d;if(e+d<=a.Ma)return a.Ja.set(b.subarray(c,c+d),e),d}Q.ub(a,e+d);if(a.Ja.subarray&&b.subarray)a.Ja.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ja[e+f]=b[c+f];a.Ma=Math.max(a.Ma,e+d);return d},Va:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ma);if(0>b)throw new P(28);return b},sb:function(a,b,c){Q.ub(a.node,
b+c);a.node.Ma=Math.max(a.node.Ma,b+c)},Bb:function(a,b,c,d,e,f){0===b||C("Assertion failed: undefined");if(32768!==(a.node.mode&61440))throw new P(43);a=a.node.Ja;if(f&2||a.buffer!==Ca){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Ab(f);c<f;)I[b+c++]=0;c=b;if(!c)throw new P(48);I.set(a,c)}else d=!1,c=a.byteOffset;return{Za:c,dc:d}},Db:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new P(43);if(e&2)return 0;
Q.La.write(a,b,0,d,c,!1);return 0}}},Bb=null,Cb={},Db=[],Eb=1,R=null,Fb=!0,S={},P=null,yb={};
function T(a,b){a=ob("/",a);b=b||{};if(!a)return{path:"",node:null};var c={vb:!0,qb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.qb)throw new P(32);a=kb(a.split("/").filter(function(h){return!!h}),!1);var e=Bb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=zb(e,a[d]);c=O(c+"/"+a[d]);e.eb&&(!f||f&&b.vb)&&(e=e.eb.root);if(!f||b.mb)for(f=0;40960===(e.mode&61440);)if(e=Gb(c),c=ob(lb(c),e),e=T(c,{qb:b.qb}).node,40<f++)throw new P(32);}return{path:c,node:e}}
function Hb(a){for(var b;;){if(a===a.parent)return a=a.Ra.Cb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ib(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.length}function zb(a,b){var c;if(c=(c=Jb(a,"x"))?c:a.Ka.ab?0:2)throw new P(c,a);for(c=R[Ib(a.id,b)];c;c=c.Xa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ka.ab(a,b)}function xb(a,b,c,d){a=new Kb(a,b,c,d);b=Ib(a.parent.id,a.name);a.Xa=R[b];return R[b]=a}
var Lb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Jb(a,b){if(Fb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Nb(a,b){try{return zb(a,b),20}catch(c){}return Jb(a,"wx")}
function Ob(a){var b=4096;for(a=a||0;a<=b;a++)if(!Db[a])return a;throw new P(33);}function Pb(a,b){Qb||(Qb=function(){},Qb.prototype={});var c=new Qb,d;for(d in a)c[d]=a[d];a=c;b=Ob(b);a.Ta=b;return Db[b]=a}var wb={open:function(a){a.La=Cb[a.node.hb].La;a.La.open&&a.La.open(a)},Va:function(){throw new P(70);}};function rb(a,b){Cb[a]={La:b}}
function Rb(a,b){var c="/"===b,d=!b;if(c&&Bb)throw new P(10);if(!c&&!d){var e=T(b,{vb:!1});b=e.path;e=e.node;if(e.eb)throw new P(10);if(16384!==(e.mode&61440))throw new P(54);}b={type:a,vc:{},Cb:b,Ub:[]};a=a.Ra(b);a.Ra=b;b.root=a;c?Bb=a:e&&(e.eb=b,e.Ra&&e.Ra.Ub.push(b))}function Sb(a,b,c){var d=T(a,{parent:!0}).node;a=mb(a);if(!a||"."===a||".."===a)throw new P(28);var e=Nb(d,a);if(e)throw new P(e);if(!d.Ka.gb)throw new P(63);return d.Ka.gb(d,a,b,c)}function U(a){Sb(a,16895,0)}
function Tb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Sb(a,b|8192,c)}function Ub(a,b){if(!ob(a))throw new P(44);var c=T(b,{parent:!0}).node;if(!c)throw new P(44);b=mb(b);var d=Nb(c,b);if(d)throw new P(d);if(!c.Ka.ib)throw new P(63);c.Ka.ib(c,b,a)}
function Vb(a){var b=T(a,{parent:!0}).node,c=mb(a),d=zb(b,c);a:{try{var e=zb(b,c)}catch(h){e=h.Sa;break a}var f=Jb(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new P(e);if(!b.Ka.jb)throw new P(63);if(d.eb)throw new P(10);try{S.willDeletePath&&S.willDeletePath(a)}catch(h){l("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Ka.jb(b,c);b=Ib(d.parent.id,d.name);if(R[b]===d)R[b]=d.Xa;else for(b=R[b];b;){if(b.Xa===d){b.Xa=d.Xa;break}b=b.Xa}try{if(S.onDeletePath)S.onDeletePath(a)}catch(h){l("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Gb(a){a=T(a).node;if(!a)throw new P(44);if(!a.Ka.fb)throw new P(28);return ob(Hb(a.parent),a.Ka.fb(a))}function Wb(a,b){var c;"string"===typeof a?c=T(a,{mb:!0}).node:c=a;if(!c.Ka.Pa)throw new P(63);c.Ka.Pa(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Xb(a,b,c,d){if(""===a)throw new P(44);if("string"===typeof b){var e=Lb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=O(a);try{f=T(a,{mb:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(f){if(b&128)throw new P(20);}else f=Sb(a,c,0),e=!0;if(!f)throw new P(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new P(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Mb(b)||b&512)?31:Jb(f,Mb(b)):44))throw new P(c);if(b&512){c=f;var h;"string"===typeof c?h=T(c,{mb:!0}).node:h=c;if(!h.Ka.Pa)throw new P(63);if(16384===(h.mode&61440))throw new P(31);if(32768!==(h.mode&61440))throw new P(28);if(c=Jb(h,"w"))throw new P(c);h.Ka.Pa(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Pb({node:f,path:Hb(f),flags:b,seekable:!0,position:0,La:f.La,bc:[],error:!1},d);d.La.open&&d.La.open(d);!g.logReadFiles||b&1||(Yb||(Yb={}),a in Yb||(Yb[a]=1,l("FS.trackingDelegate error on read file: "+
a)));try{S.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),S.onOpenFile(a,f))}catch(k){l("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function Zb(a){if(null===a.Ta)throw new P(8);a.nb&&(a.nb=null);try{a.La.close&&a.La.close(a)}catch(b){throw b;}finally{Db[a.Ta]=null}a.Ta=null}
function $b(a,b,c){if(null===a.Ta)throw new P(8);if(!a.seekable||!a.La.Va)throw new P(70);if(0!=c&&1!=c&&2!=c)throw new P(28);a.position=a.La.Va(a,b,c);a.bc=[]}
function ac(a,b,c,d,e,f){if(0>d||0>e)throw new P(28);if(null===a.Ta)throw new P(8);if(0===(a.flags&2097155))throw new P(8);if(16384===(a.node.mode&61440))throw new P(31);if(!a.La.write)throw new P(28);a.seekable&&a.flags&1024&&$b(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new P(70);b=a.La.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&S.onWriteToFile)S.onWriteToFile(a.path)}catch(k){l("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
k.message)}return b}function bc(){P||(P=function(a,b){this.node=b;this.Wb=function(c){this.Sa=c};this.Wb(a);this.message="FS error"},P.prototype=Error(),P.prototype.constructor=P,[44].forEach(function(a){yb[a]=new P(a);yb[a].stack="<generic error, no stack>"}))}var cc;function dc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function ec(a,b){a="string"===typeof a?a:Hb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=O(a+"/"+c);try{U(d)}catch(e){}a=d}}return d}
function fc(a,b,c,d){a=O(("string"===typeof a?a:Hb(a))+"/"+b);c=dc(c,d);return Sb(a,(void 0!==c?c:438)&4095|32768,0)}function gc(a,b,c,d,e,f){a=b?O(("string"===typeof a?a:Hb(a))+"/"+b):a;d=dc(d,e);e=Sb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Wb(e,d|146);a=Xb(e,"w");ac(a,c,0,c.length,0,f);Zb(a);Wb(e,d)}return e}
function V(a,b,c,d){a=O(("string"===typeof a?a:Hb(a))+"/"+b);b=dc(!!c,!!d);V.Ab||(V.Ab=64);var e=V.Ab++<<8|0;rb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,k,n){for(var u=0,v=0;v<n;v++){try{var t=c()}catch(p){throw new P(29);}if(void 0===t&&0===u)throw new P(6);if(null===t||void 0===t)break;u++;h[k+v]=t}u&&(f.node.timestamp=Date.now());return u},write:function(f,h,k,n){for(var u=0;u<n;u++)try{d(h[k+u])}catch(v){throw new P(29);}n&&(f.node.timestamp=
Date.now());return u}});return Tb(a,b,e)}
function hc(a){if(a.zb||a.Sb||a.link||a.Ja)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ra)try{a.Ja=tb(ra(a.url)),a.Ma=a.Ja.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||(J[ic()>>2]=29);return b}
function jc(a,b,c,d,e){if("undefined"!==typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={zb:!1,url:c};var f=fc(a,b,d,e);c.Ja?f.Ja=c.Ja:c.url&&(f.Ja=null,f.url=c.url);Object.defineProperties(f,{Ma:{get:function(){return this.Ja.length}}});var h={};Object.keys(f.La).forEach(function(k){var n=f.La[k];h[k]=function(){if(!hc(f))throw new P(29);return n.apply(null,arguments)}});h.read=function(k,n,u,v,t){if(!hc(f))throw new P(29);
k=k.node.Ja;if(t>=k.length)return 0;v=Math.min(k.length-t,v);if(k.slice)for(var p=0;p<v;p++)n[u+p]=k[t+p];else for(p=0;p<v;p++)n[u+p]=k.get(t+p);return v};f.La=h;return f}function kc(a,b,c,d,e,f,h,k,n,u){function v(w){function D(E){u&&u();k||gc(a,b,E,d,e,n);f&&f();Va(p)}var M=!1;g.preloadPlugins.forEach(function(E){!M&&E.canHandle(t)&&(E.handle(w,t,D,function(){h&&h();Va(p)}),M=!0)});M||D(w)}lc.yb();var t=b?ob(O(a+"/"+b)):a,p="cp "+t;Ua(p);"string"==typeof c?lc.ec(c,function(w){v(w)},h):v(c)}
var W={},Qb,Yb,mc=void 0;function nc(){mc+=4;return J[mc-4>>2]}function oc(a){a=Db[a];if(!a)throw new P(8);return a}function pc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function qc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function rc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var sc=1,tc=[],X=[],uc=[],vc=[],wc=[],Y=[],db=[],xc={},yc={},zc=4;
function Z(a){Ac||(Ac=a)}function cb(a){for(var b=sc++,c=a.length;c<b;c++)a[c]=null;return b}
function eb(a){a||(a=fb);if(!a.Qb){a.Qb=!0;var b=a.rb;pc(b);qc(b);rc(b);b.lc=b.getExtension("EXT_disjoint_timer_query");b.tc=b.getExtension("WEBGL_multi_draw");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod EXT_texture_norm16 WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");(b.getSupportedExtensions()||
[]).forEach(function(d){-1!=c.indexOf(d)&&b.getExtension(d)})}}var Ac,fb;function Bc(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),h=f&&cb(d);f?(f.name=h,d[h]=f):Z(1282);J[b+4*e>>2]=h}}
function Cc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&Z(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Z(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:Z(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:J[b+4*a>>2]=e[a];break;case 2:K[b+4*a>>2]=e[a];break;case 4:I[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){Z(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:Z(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:c=
d;Fa[b>>2]=c;Fa[b+4>>2]=(c-Fa[b>>2])/4294967296;break;case 0:J[b>>2]=d;break;case 2:K[b>>2]=d;break;case 4:I[b>>0]=d?1:0}}else Z(1281)}function Dc(a){var b=za(a)+1,c=Ab(b);H(a,G,c,b);return c}function Ec(a,b,c,d,e){a-=5120;a=1==a?G:4==a?J:6==a?K:5==a||28922==a?Fa:Ea;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),h=zc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+h-1&-h)>>f)}var Fc=[],Gc=[];
function Kb(a,b,c,d){a||(a=this);this.parent=a;this.Ra=a.Ra;this.eb=null;this.id=Eb++;this.name=b;this.mode=c;this.Ka={};this.La={};this.hb=d}Object.defineProperties(Kb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Sb:{get:function(){return 16384===(this.mode&61440)}},zb:{get:function(){return 8192===(this.mode&61440)}}});bc();
R=Array(4096);Rb(Q,"/");U("/tmp");U("/home");U("/home/web_user");(function(){U("/dev");rb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Tb("/dev/null",259);qb(1280,ub);qb(1536,vb);Tb("/dev/tty",1280);Tb("/dev/tty1",1536);var a=nb();V("/dev","random",a);V("/dev","urandom",a);U("/dev/shm");U("/dev/shm/tmp")})();U("/proc");U("/proc/self");U("/proc/self/fd");
Rb({Ra:function(){var a=xb("/proc/self","fd",16895,73);a.Ka={ab:function(b,c){var d=Db[+c];if(!d)throw new P(8);b={parent:null,Ra:{Cb:"fake"},Ka:{fb:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");var lc;g.FS_createPath=ec;g.FS_createDataFile=gc;g.FS_createPreloadedFile=kc;g.FS_createLazyFile=jc;g.FS_createDevice=V;g.FS_unlink=Vb;for(var N,Hc=new Float32Array(288),Ic=0;288>Ic;++Ic)Fc[Ic]=Hc.subarray(0,Ic+1);
function tb(a){var b=Array(za(a)+1);a=H(a,b,0,b.length);b.length=a;return b}Ka.push({Pb:function(){Jc()}});
var Lc={ra:function(a){return Ab(a+16)+16},qa:function(a,b,c){(new ib(a)).yb(b,c);"uncaught_exception"in jb?jb.Ib++:jb.Ib=1;throw a;},m:function(a,b,c){mc=c;try{var d=oc(a);switch(b){case 0:var e=nc();return 0>e?-28:Xb(d.path,d.flags,0,e).Ta;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=nc(),d.flags|=e,0;case 12:return e=nc(),Da[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return J[ic()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof W&&f instanceof
P||C(f),-f.Sa}},I:function(a,b,c){mc=c;try{var d=oc(a);switch(b){case 21509:case 21505:return d.Na?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Na?0:-59;case 21519:if(!d.Na)return-59;var e=nc();return J[e>>2]=0;case 21520:return d.Na?-28:-59;case 21531:a=e=nc();if(!d.La.Rb)throw new P(59);return d.La.Rb(d,b,a);case 21523:return d.Na?0:-59;case 21524:return d.Na?0:-59;default:C("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof W&&f instanceof P||C(f),
-f.Sa}},J:function(a,b,c){mc=c;try{var d=ya(a),e=nc();return Xb(d,b,e).Ta}catch(f){return"undefined"!==typeof W&&f instanceof P||C(f),-f.Sa}},F:function(){C()},o:function(a,b,c){Gc.length=0;var d;for(c>>=2;d=G[b++];)(d=105>d)&&c&1&&c++,Gc.push(d?Ga[c++>>1]:J[c]),++c;return gb[a].apply(null,Gc)},D:function(a,b,c){G.copyWithin(a,b,b+c)},c:function(a){a>>>=0;var b=G.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=
65536-d%65536);a:{try{F.grow(Math.min(2147483648,d)-Ca.byteLength+65535>>>16);Ha(F.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},K:function(a){Kc(a)},n:function(a){try{var b=oc(a);Zb(b);return 0}catch(c){return"undefined"!==typeof W&&c instanceof P||C(c),c.Sa}},H:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var h=J[b+(8*f+4)>>2],k=e,n=J[b+8*f>>2],u=h,v=void 0,t=I;if(0>u||0>v)throw new P(28);if(null===k.Ta)throw new P(8);if(1===(k.flags&2097155))throw new P(8);if(16384===
(k.node.mode&61440))throw new P(31);if(!k.La.read)throw new P(28);var p="undefined"!==typeof v;if(!p)v=k.position;else if(!k.seekable)throw new P(70);var w=k.La.read(k,t,n,u,v);p||(k.position+=w);var D=w;if(0>D){var M=-1;break a}a+=D;if(D<h)break}M=a}J[d>>2]=M;return 0}catch(E){return"undefined"!==typeof W&&E instanceof P||C(E),E.Sa}},G:function(a,b,c,d){try{var e=Number(b&BigInt(4294967295))|0,f=Number(b>>BigInt(32))|0,h=oc(a);a=4294967296*f+(e>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;
$b(h,a,c);bb=[h.position>>>0,(ab=h.position,1<=+Oa(ab)?0<ab?(Ra(+Qa(ab/4294967296),4294967295)|0)>>>0:~~+Pa((ab-+(~~ab>>>0))/4294967296)>>>0:0)];J[d>>2]=bb[0];J[d+4>>2]=bb[1];h.nb&&0===a&&0===c&&(h.nb=null);return 0}catch(k){return"undefined"!==typeof W&&k instanceof P||C(k),k.Sa}},l:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var h=ac(e,I,J[b+8*f>>2],J[b+(8*f+4)>>2],void 0);if(0>h){var k=-1;break a}a+=h}k=a}J[d>>2]=k;return 0}catch(n){return"undefined"!==typeof W&&n instanceof P||C(n),
n.Sa}},k:function(a){N.activeTexture(a)},f:function(a,b){N.attachShader(X[a],Y[b])},aa:function(a,b,c){N.bindAttribLocation(X[a],b,ya(c))},d:function(a,b){N.bindBuffer(a,tc[b])},ga:function(a,b){N.bindFramebuffer(a,uc[b])},g:function(a,b){N.bindTexture(a,vc[b])},W:function(a,b,c,d){N.blendFuncSeparate(a,b,c,d)},i:function(a,b,c,d){N.bufferData(a,c?G.subarray(c,c+b):b,d)},N:function(a,b,c,d){N.bufferSubData(a,b,G.subarray(d,d+c))},ha:function(a){N.clear(a)},ma:function(a,b,c,d){N.clearColor(a,b,c,
d)},ka:function(a){N.clearDepth(a)},ia:function(a){N.clearStencil(a)},z:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},S:function(a){N.compileShader(Y[a])},P:function(a,b,c,d,e,f,h,k){N.compressedTexImage2D(a,b,c,d,e,f,k?G.subarray(k,k+h):null)},ba:function(){var a=cb(X),b=N.createProgram();b.name=a;X[a]=b;return a},U:function(a){var b=cb(Y);Y[b]=N.createShader(a);return b},v:function(a){N.cullFace(a)},Q:function(a,b){for(var c=0;c<a;c++){var d=J[b+4*c>>2],e=vc[d];e&&(N.deleteTexture(e),e.name=0,
vc[d]=null)}},X:function(a){N.depthFunc(a)},la:function(a){N.depthMask(!!a)},h:function(a){N.disable(a)},M:function(a){N.disableVertexAttribArray(a)},oa:function(a,b,c,d){N.drawElements(a,b,c,d)},e:function(a){N.enable(a)},q:function(a){N.enableVertexAttribArray(a)},fa:function(){N.flush()},w:function(a,b){Bc(a,b,"createBuffer",tc)},t:function(a,b){Bc(a,b,"createTexture",vc)},V:function(a,b,c,d,e,f,h){a=X[a];if(b=N.getActiveUniform(a,b))c=h&&H(b.name,G,h,c),d&&(J[d>>2]=c),e&&(J[e>>2]=b.size),f&&(J[f>>
2]=b.type)},da:function(a,b){Cc(a,b,2)},C:function(a,b){Cc(a,b,0)},_:function(a,b,c,d){a=N.getProgramInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,G,d,b):0;c&&(J[c>>2]=b)},j:function(a,b,c){if(c)if(a>=sc)Z(1281);else{var d=xc[a];if(d)if(35716==b)a=N.getProgramInfoLog(X[a]),null===a&&(a="(unknown error)"),J[c>>2]=a.length+1;else if(35719==b)J[c>>2]=d.ob;else if(35722==b){if(-1==d.bb){a=X[a];var e=N.getProgramParameter(a,35721);for(b=d.bb=0;b<e;++b)d.bb=Math.max(d.bb,N.getActiveAttrib(a,
b).name.length+1)}J[c>>2]=d.bb}else if(35381==b){if(-1==d.cb)for(a=X[a],e=N.getProgramParameter(a,35382),b=d.cb=0;b<e;++b)d.cb=Math.max(d.cb,N.getActiveUniformBlockName(a,b).length+1);J[c>>2]=d.cb}else J[c>>2]=N.getProgramParameter(X[a],b);else Z(1282)}else Z(1281)},R:function(a,b,c,d){a=N.getShaderInfoLog(Y[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,G,d,b):0;c&&(J[c>>2]=b)},u:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(Y[a]),null===a&&(a="(unknown error)"),J[c>>2]=a?a.length+1:0):35720==
b?(a=N.getShaderSource(Y[a]),J[c>>2]=a?a.length+1:0):J[c>>2]=N.getShaderParameter(Y[a],b):Z(1281)},E:function(a){if(yc[a])return yc[a];switch(a){case 7939:var b=N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Dc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||Z(1280);b=Dc(b);break;case 7938:b=Dc("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Dc(b);break;default:return Z(1280),0}return yc[a]=b},x:function(a,b){b=ya(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=xc[a]&&xc[a].Jb[b])&&0<=c&&c<a[0]?a[1]+c:-1},$:function(a){N.linkProgram(X[a]);var b=X[a];a=xc[a]={Jb:{},ob:0,bb:-1,cb:-1};for(var c=a.Jb,d=N.getProgramParameter(b,35718),e=0;e<d;++e){var f=N.getActiveUniform(b,e),h=f.name;a.ob=
Math.max(a.ob,h.length+1);"]"==h.slice(-1)&&(h=h.slice(0,h.lastIndexOf("[")));var k=N.getUniformLocation(b,h);if(k){var n=cb(wc);c[h]=[f.size,n];wc[n]=k;for(var u=1;u<f.size;++u)k=N.getUniformLocation(b,h+"["+u+"]"),n=cb(wc),wc[n]=k}}},r:function(a,b){3317==a&&(zc=b);N.pixelStorei(a,b)},na:function(a,b,c,d){N.scissor(a,b,c,d)},T:function(a,b,c,d){for(var e="",f=0;f<b;++f){var h=d?J[d+4*f>>2]:-1;e+=ya(J[c+4*f>>2],0>h?void 0:h)}N.shaderSource(Y[a],e)},ea:function(a,b,c){N.stencilFunc(a,b,c)},y:function(a){N.stencilMask(a)},
Y:function(a,b,c){N.stencilOp(a,b,c)},s:function(a,b,c,d,e,f,h,k,n){N.texImage2D(a,b,c,d,e,f,h,k,n?Ec(k,h,d,e,n):null)},ca:function(a,b,c){N.texParameterf(a,b,c)},b:function(a,b,c){N.texParameteri(a,b,c)},O:function(a,b,c,d,e,f,h,k,n){var u=null;n&&(u=Ec(k,h,e,f,n));N.texSubImage2D(a,b,c,d,e,f,h,k,u)},B:function(a,b){N.uniform1i(wc[a],b)},pa:function(a,b,c,d){if(32>=b)for(var e=Fc[9*b-1],f=0;f<9*b;f+=9)e[f]=K[d+4*f>>2],e[f+1]=K[d+(4*f+4)>>2],e[f+2]=K[d+(4*f+8)>>2],e[f+3]=K[d+(4*f+12)>>2],e[f+4]=K[d+
(4*f+16)>>2],e[f+5]=K[d+(4*f+20)>>2],e[f+6]=K[d+(4*f+24)>>2],e[f+7]=K[d+(4*f+28)>>2],e[f+8]=K[d+(4*f+32)>>2];else e=K.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(wc[a],!!c,e)},Z:function(a){N.useProgram(X[a])},p:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},A:function(a,b,c,d){N.viewport(a,b,c,d)},L:function(a,b){ba(a,b)},ja:function(){return window.performance.now()/1E3},a:F};
(function(){function a(e){g.asm=e.exports;ua=g.asm.sa;Va("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return $a().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){l("failed to asynchronously prepare wasm: "+f);C(f)})}var d={a:Lc};Ua("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return l("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(ta||"function"!==typeof WebAssembly.instantiateStreaming||
Wa()||"function"!==typeof fetch)return c(b);fetch(Xa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){l("wasm streaming compile failed: "+f);l("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Jc=g.___wasm_call_ctors=function(){return(Jc=g.___wasm_call_ctors=g.asm.ta).apply(null,arguments)},Ab=g._malloc=function(){return(Ab=g._malloc=g.asm.ua).apply(null,arguments)},la=g._js_update_display=function(){return(la=g._js_update_display=g.asm.va).apply(null,arguments)},ea=g._js_event_mouse=function(){return(ea=g._js_event_mouse=g.asm.wa).apply(null,arguments)},fa=g._js_event_wheel=function(){return(fa=g._js_event_wheel=g.asm.xa).apply(null,arguments)},da=g._js_event_key=function(){return(da=
g._js_event_key=g.asm.ya).apply(null,arguments)},z=g._js_event_touch=function(){return(z=g._js_event_touch=g.asm.za).apply(null,arguments)},ia=g._js_event_gamepad_axis=function(){return(ia=g._js_event_gamepad_axis=g.asm.Aa).apply(null,arguments)},ja=g._js_event_gamepad_button=function(){return(ja=g._js_event_gamepad_button=g.asm.Ba).apply(null,arguments)},ka=g._js_loop=function(){return(ka=g._js_loop=g.asm.Ca).apply(null,arguments)};
g.___em_js__js_init=function(){return(g.___em_js__js_init=g.asm.Da).apply(null,arguments)};g.___em_js__kinc_time=function(){return(g.___em_js__kinc_time=g.asm.Ea).apply(null,arguments)};var ma=g._js_event_resize=function(){return(ma=g._js_event_resize=g.asm.Fa).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Ga).apply(null,arguments)};
var ic=g.___errno_location=function(){return(ic=g.___errno_location=g.asm.Ha).apply(null,arguments)},Ba=g.stackAlloc=function(){return(Ba=g.stackAlloc=g.asm.Ia).apply(null,arguments)};g.addRunDependency=Ua;g.removeRunDependency=Va;g.FS_createPath=ec;g.FS_createDataFile=gc;g.FS_createPreloadedFile=kc;g.FS_createLazyFile=jc;g.FS_createDevice=V;g.FS_unlink=Vb;var Mc;function Nc(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
Ta=function Oc(){Mc||Pc();Mc||(Ta=Oc)};
function Pc(a){function b(){if(!Mc&&(Mc=!0,g.calledRun=!0,!va)){g.noFSInit||cc||(cc=!0,bc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?V("/dev","stdin",g.stdin):Ub("/dev/tty","/dev/stdin"),g.stdout?V("/dev","stdout",null,g.stdout):Ub("/dev/tty","/dev/stdout"),g.stderr?V("/dev","stderr",null,g.stderr):Ub("/dev/tty1","/dev/stderr"),Xb("/dev/stdin","r"),Xb("/dev/stdout","w"),Xb("/dev/stderr","w"));hb(Ka);Fb=!1;hb(La);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Qc){var c=a,
d=g._main;c=c||[];var e=c.length+1,f=Ba(4*(e+1));J[f>>2]=Aa(pa);for(var h=1;h<e;h++)J[(f>>2)+h]=Aa(c[h-1]);J[(f>>2)+e]=0;try{var k=d(e,f);Kc(k,!0)}catch(n){n instanceof Nc||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),l("exception thrown: "+c),qa(1,n)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Ma.unshift(c);hb(Ma)}}a=a||oa;if(!(0<L)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=
[g.preRun]);g.preRun.length;)Na();hb(Ja);0<L||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=Pc;function Kc(a,b){if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);va=!0}qa(a,new Nc(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Qc=!0;g.noInitialRun&&(Qc=!1);noExitRuntime=!0;Pc();
